title: "Evan Ditter"
author: "Evan Ditter"
description: "Evan Ditter"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "cv.md", title: "CV/Resume"}
  - {file: "bio.md", "About me"}
  - {file: "digital.md", title: "Digital Humanities Projects"}
    subfolderitems:
      -{file: "curate.md", title: "Curated Collections"}
      -{file: "hand.md", title: "Handwritten Text Recognition"}
      -{file: "digital.md", title: "Digital Storytelling"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:editter@princeton.edu"}
  - {title: Github, icon: github, url: "https://github.com/evandttr"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
